import '../styles/globals.css';
import '../styles/prism-nord.css';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import SlimeLoading from '../components/SlimeLoading';

const MyApp = ({ Component, pageProps }) => {
  const router = useRouter();
  const [pageLoading, setPageLoading] = useState(false);

  useEffect(() => {
    const handleStart = () => setPageLoading(true);
    const handleComplete = () => setPageLoading(false);

    router.events.on('routeChangeStart', handleStart);
    router.events.on('routeChangeComplete', handleComplete);
    router.events.on('routeChangeError', handleComplete);
  }, [router]);

  return (
    <>
      <Head>
        <title>AsGoshawk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        {pageLoading ? (
          <div className='min-h-screen flex items-center justify-center'>
            <SlimeLoading />
          </div>
        ) : (
          <Component {...pageProps} />
        )}
      </Layout>
    </>
  );
};

export default MyApp;
