import Head from 'next/head';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import ScrollTrigger from 'react-scroll-trigger';
import { FaLinkedin, FaGithub, FaCopyright, FaBlackTie, FaGraduationCap, FaSearch } from 'react-icons/fa';
import {
  SiReact,
  SiTailwindcss,
  SiExpress,
  SiMongodb,
  SiInfluxdb,
  SiFirebase,
  SiPython,
  SiJavascript,
  SiCplusplus,
  SiGnubash,
  SiLinux,
  SiRaspberrypi,
  SiDocker,
  SiBlender,
  SiAutodesk,
} from 'react-icons/si';
import ClipStudioPaint from '../public/assets/svg/clip-studio.svg';
import CircleProgress from '../components/CircleProgress';
import Expbar from '../components/Expbar';
import BackgroundImg from '../public/assets/png/street-rain.jpg';

const Profile = () => {
  const router = useRouter();

  useEffect(() => {
    // console.log(router.asPath.replace('/', ''));
    if (router.asPath.replace('/', '')) {
      let elem = document.getElementById(router.asPath.replace('/', ''));
      if (elem) {
        elem.scrollIntoView({ behavior: 'smooth' });
      }
    } else {
      window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>AsGoshawk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full min-h-screen flex flex-col items-center justify-start pb-8'>
        <Banner />
        <About />
        <Skills />
        <Experience />
        <Education />
      </div>
    </>
  );
};

const Banner = () => {
  return (
    <div
      className='relative w-full h-screen pt-16 lg:pl-40 flex flex-col items-center justify-center bg-scroll bg-bottom bg-cover bg-no-repeat'
      style={{ backgroundImage: `url(${BackgroundImg.src})` }}
    >
      <div className='w-full md:w-5/6 lg:w-4/5 md:max-w-3xl h-48 sm:h-60 relative py-4 sm:py-2 mx-4 mt-32 md:mx-0 md:mt-0 bg-slate-700/40 rounded-none md:rounded-full flex flex-col md:items-end justify-evenly'>
        <div
          className='absolute rounded-full w-60 h-60 lg:w-80 lg:h-80 -top-56 inset-x-0 mx-auto  
                            md:left-0 md:top-auto md:mx-0 lg:-left-40 shadow-2xl overflow-hidden'
        >
          <img src='https://avatars.githubusercontent.com/u/42184309' alt='' />
        </div>
        <p className='text-lg sm:text-xl lg:text-2xl text-gray-300 mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          Hi there! I am
        </p>
        <h1 className='text-3xl sm:text-4xl lg:text-5xl font-bold text-primary mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          Ching-Wei Chu
        </h1>
        <p className='text-lg sm:text-xl lg:text-2xl text-gray-300 mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          A web developer from Taiwan.
        </p>
        <ul className='flex flex-wrap items-center text-sm text-gray-300 mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          <li className='mr-4 md:mr-6 py-[auto]'>
            <a
              href='https://github.com/asgoshawk'
              className='block hover:text-primary transition-color ease-in-out duration-300'
              target='_blank'
              rel='noreferrer noopener'
            >
              <FaGithub className='text-2xl' />
            </a>
          </li>
          <li className='mr-4 md:mr-6 py-[auto]'>
            <a
              href='https://linkedin.com/in/asgoshawk'
              className='block hover:text-primary transition-color ease-in-out duration-300'
              target='_blank'
              rel='noreferrer noopener'
            >
              <FaLinkedin className='text-2xl' />
            </a>
          </li>
          <li className=''>
            <a
              href='https://cakeresume.com/me/asgoshawk'
              className='block hover:text-primary transition-color ease-in-out duration-300'
              target='_blank'
              rel='noreferrer noopener'
            >
              <FaCopyright className='text-2xl' />
            </a>
          </li>
        </ul>
      </div>
      <Link href='#about'>
        <a
          className='relative text-primary text-lg px-5 py-2 mt-6 sm:mt-16 rounded-lg border-primary border-2
                    hover:text-slate-900 hover:bg-primary/60 top-0 hover:top-0.5 transition-all ease-in-out duration-800'
        >
          About Me
        </a>
      </Link>
    </div>
  );
};

const About = () => {
  const [trigger1, setTrigger1] = useState(false);

  const getAge = () => {
    const today = new Date();
    const yearNow = today.getFullYear();
    const birthDate = new Date(1994, 11, 12); // 11 for Dec.
    const dumDate = birthDate;
    dumDate.setFullYear(yearNow - 1);
    const daysOfYear = (yearNow % 4 === 0 && yearNow % 100 !== 0) || yearNow % 400 === 0 ? 366 : 365;
    const diffDays = (today - dumDate) / 86400000 / daysOfYear;
    let ageYear = today.getFullYear() - 1994 - 1;
    if (diffDays >= 1) {
      ageYear += 1;
    }
    return { ageQ: ageYear, ageR: diffDays % 1 };
  };

  const { ageQ, ageR } = getAge();

  return (
    <div className='relative w-full mb-8 mt-16 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <div id='about' className='absolute -top-16 left-0'></div>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 py-8'>ABOUT</h1>

      <div className='flex flex-col md:flex-row items-center md:items-start px-0 sm:px-12 md:px-4'>
        <div className='w-full md:w-1/3'>
          <div className='rounded-2xl w-full max-w-sm mb-2 aspect-square mx-auto md:mx-0 shadow-2xl overflow-hidden'>
            <img className='w-full' src='https://avatars.githubusercontent.com/u/42184309' alt='' />
          </div>
          <ScrollTrigger className='relative flex flex-col items-center' onEnter={() => setTrigger1(true)}>
            <div className='w-full m-2'>
              <p className='mb-2 text-xl md:text-md text-slate-800 dark:text-gray-300'>Lv. {ageQ}</p>
              <Expbar width={ageR * 100} barColor={'bg-secondary dark:bg-primary'} isTrigger={trigger1} />
            </div>
            <div className='w-full flex items-center justify-between my-8 md:my-4'>
              <AbilityItem text='STR' value={30} trigger={trigger1} />
              <AbilityItem text='DEF' value={40} trigger={trigger1} />
              <AbilityItem text='INT' value={80} trigger={trigger1} />
              <AbilityItem text='DEX' value={60} trigger={trigger1} />
              <AbilityItem text='LUK' value={50} trigger={trigger1} />
            </div>
          </ScrollTrigger>
        </div>

        <div className='w-full h-fullsm:text-base md:grow-1 flex flex-col md:pl-12 md:mt-0 text-slate-800 dark:text-gray-300 justify-between'>
          <div className='text-left sm:text-justify mb-6'>
            Familiar with <strong>Python</strong> and <strong>JavaScript</strong>, and mainly deveolping with{' '}
            <strong>React</strong> and <strong>Tailwind CSS</strong> recently. Interested in learning new things and can
            quickly get the hang of them most of the time. Good at developing IoT prototype using{' '}
            <strong>Raspberry Pi</strong> and <strong>Pico</strong>. Currently learning <strong>Next.js</strong> and the{' '}
            <strong>MERN</strong> framework.
          </div>
          <div className='text-left sm:text-justify mb-6'>
            During the Research and Development Subtstitute Services (RDSS) in National Taiwan University, spent about{' '}
            <strong>1+ years</strong> self-studying and developed monitoring website for air quality box from data
            logger to <strong>full stack</strong> application including <strong>database</strong> and{' '}
            <strong>API</strong> builds.
          </div>
          <div className='text-left sm:text-justify'>
            A nerdy guy, but open-minded, creative, and patient in teaching people technologies. Having lots of hobbies
            such as plastic model and digital art; usually enjoying side projects, 3A games, and anime in the spare
            time.
          </div>
        </div>
      </div>
    </div>
  );
};

const AbilityItem = ({ text, value, trigger }) => {
  return (
    <div className='relative aspect-square w-12 sm:w-16 md:w-10 rounded-full shadow-lg'>
      <div
        className='absolute h-auto w-auto inset-0 m-1 rounded-full flex items-center justify-center
                        bg-slate-200 dark:bg-slate-800 shadow-28 z-10 text-slate-800 dark:text-gray-300 text-sm md:text-xs'
      >
        {text}
      </div>
      <CircleProgress dashOffset={value} strokeColor={'stroke-secondary dark:stroke-primary'} trigger={trigger} />
    </div>
  );
};

const Skills = () => {
  const [trigger, setTrigger] = useState(false);
  return (
    <div className='relative w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 pb-2'>SKILLS</h1>
      <ScrollTrigger
        className='w-full my-2 lg:grid lg:grid-cols-2 lg:gap-2'
        onEnter={() => setTrigger(true)}
        // onExit={() => setTrigger(false)}
      >
        <div
          className='relative w-full px-0 sm:px-4 py-4 rounded-2xl top-0 left-0
                     hover:shadow-lg hover:top-0 hover:left-0 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>Web Development</h1>
          <SkillItem text={'React'} percent={60} trigger={trigger} icon={<SiReact />} showLink={true} tag='React' />
          <SkillItem
            text={'Tailwind CSS'}
            percent={55}
            trigger={trigger}
            icon={<SiTailwindcss />}
            showLink={true}
            tag='Tailwindcss'
          />
          <SkillItem
            text={'Express / Node.js'}
            percent={50}
            trigger={trigger}
            icon={<SiExpress />}
            showLink={true}
            tag='Express'
          />
          <SkillItem
            text={'InfluxDB'}
            percent={50}
            trigger={trigger}
            icon={<SiInfluxdb />}
            showLink={true}
            tag='InfluxDB'
          />
          <SkillItem
            text={'MongoDB'}
            percent={45}
            trigger={trigger}
            icon={<SiMongodb />}
            showLink={true}
            tag='MongoDB'
          />
          {/* <SkillItem text={'Firebase'} percent={40} trigger={trigger} icon={<SiFirebase />} /> */}
        </div>

        <div
          className='relative w-full px-0 sm:px-4 py-4 rounded-2xl top-0 left-0
                                hover:shadow-lg hover:top-0 hover:left-0 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>Programing Language</h1>
          <SkillItem text={'Python'} percent={65} trigger={trigger} icon={<SiPython />} showLink={true} tag='Python' />
          <SkillItem
            text={'JavaScript'}
            percent={60}
            trigger={trigger}
            icon={<SiJavascript />}
            showLink={true}
            tag='JavaScript'
          />
          <SkillItem text={'C / C++'} percent={40} trigger={trigger} icon={<SiCplusplus />} />
          {/* <SkillItem text={'Bash Script'} percent={40} trigger={trigger} icon={<SiGnubash />} /> */}
        </div>

        <div
          className='relative w-full px-0 sm:px-4 py-4 rounded-2xl top-0 left-0
                                hover:shadow-lg hover:top-0 hover:left-0 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>System & Software</h1>
          <SkillItem text={'Linux'} percent={70} trigger={trigger} icon={<SiLinux />} />
          <SkillItem
            text={'Raspberry Pi'}
            percent={65}
            trigger={trigger}
            icon={<SiRaspberrypi />}
            showLink={true}
            tag='RaspberryPi'
          />
          <SkillItem text={'Docker'} percent={40} trigger={trigger} icon={<SiDocker />} />
        </div>

        <div
          className='relative w-full px-0 sm:px-4 py-4 rounded-2xl top-0 left-0
                                hover:shadow-lg hover:top-0 hover:left-0 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>Other</h1>
          <SkillItem text={'Clip Studio Paint'} percent={50} trigger={trigger} icon={<ClipStudioPaint />} />
          <SkillItem text={'AutoCAD'} percent={50} trigger={trigger} icon={<SiAutodesk />} />
          <SkillItem
            text={'Blender'}
            percent={45}
            trigger={trigger}
            icon={<SiBlender />}
            showLink={true}
            tag='Blender'
          />
          {/* <SkillItem text={"DaVinci Resolve"} percent={60} trigger={trigger} /> */}
        </div>
      </ScrollTrigger>
    </div>
  );
};

const SkillItem = ({ text, icon, percent, showLink = false, tag = '', trigger }) => {
  return (
    <div className='mx-auto w-11/12 sm:w-5/6 my-4 flex items-center wrap justify-center'>
      <div className='text-2xl text-slate-800 dark:text-gray-300 mr-8'>{icon}</div>
      <div className='w-5/6'>
        <div className='flex items-center justify-between'>
          {showLink ? (
            <Link href={`projects?tag=${tag}`}>
              <a className='mb-1 text-md text-slate-800 dark:text-gray-300 flex items-center'>
                {text}
                <FaSearch className='ml-2 text-xs' />
              </a>
            </Link>
          ) : (
            <p className='mb-1 text-md text-slate-800 dark:text-gray-300'>{text}</p>
          )}
          <p className='mb-1 text-md text-slate-800 dark:text-gray-300 '>{percent} %</p>
        </div>
        <Expbar width={percent} barColor={'bg-secondary dark:bg-primary'} isTrigger={trigger} />
      </div>
    </div>
  );
};

const Experience = () => {
  return (
    <div className='w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 py-4'>EXPERIENCE</h1>
      <ul className='relative ml-4 sm:ml-auto w-11/12 my-4 border-l-2 border-gray-400 dark:border-gray-500'>
        <li className='mb-10 ml-6 sm:ml-10 '>
          <span
            className='absolute w-8 h-8 flex items-center justify-center rounded-full -left-4 ring-8 
                                   ring-slate-200 dark:ring-slate-800 bg-secondary dark:bg-primary'
          >
            <FaBlackTie className='text-[1.2rem] text-surface dark:text-background' />
          </span>
          <h3 className=' flex items-center mb-1 text-xl sm:text-3xl font-medium text-slate-800 dark:text-gray-300'>
            Research Assistant (RDSS)
          </h3>
          <h3 className=' flex items-center mb-1 text-lg sm:text-xl font-medium text-secondary dark:text-primary'>
            National Taiwan University
          </h3>
          <time className='flex items-center mb-2 text-lg font-normal text-gray-400 dark:text-gray-500'>
            Sep. 2020 - May 2022
          </time>
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <p className='mb-1 font-semibold'>Instrument Development</p>
            <li className='ml-4 mb-2'>Build air sampling system and prepare control GUI using Tkinter.</li>
            <li className='ml-4 mb-2'>
              Build dashboard website for Air Quality Box (AQB) using common JavaScript/CSS/HTML.
            </li>
            <li className='ml-4 mb-2'>
              Handle AQB data restoration using Docker-based InfluxDB, and build API for dashboard with Node.js.
            </li>
            <li className='ml-4 mb-2'>
              Improve the housing of AQB with 3D-printed cover (Blender) and acryic mounting board (AutoCAD).
            </li>
            <li className='ml-4 mb-2'>Improve remote connection issue in field study with openVPN.</li>
          </ul>
          <br />
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <p className='mb-1 font-semibold'>Computing Machine Maintenance</p>
            <li className='ml-4 mb-2'>Hardware build and operating system (CentOS and Ubuntu) installation.</li>
            <li className='ml-4 mb-2'>Compile and test 16 softwares.</li>
          </ul>
          <br />
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <p className='mb-1 font-semibold'>Others</p>
            <li className='ml-4 mb-2'>
              Prepare <span>
              <a
                href='https://asgoshawk.github.io/NTUAS2021_AirPollutionLab/docs'
                className='underline inline'
                target='_blank'
                rel='noreferrer noopener'
              >
                air pollution hands-on course
              </a>
              </span> with Raspberry Pi.
            </li>
            <li className='ml-4 mb-2'>Scientific manuscript of model simulation.</li>
          </ul>
        </li>
      </ul>
    </div>
  );
};

const Education = () => {
  return (
    <div className='w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 py-4'>EDUCATION</h1>
      <ul className='relative ml-4 sm:ml-auto w-11/12 my-4 border-l-2 border-gray-400 dark:border-gray-500'>
        <li className='mb-10 ml-6 sm:ml-10 '>
          <span
            className='absolute w-8 h-8 flex items-center justify-center rounded-full -left-4 ring-8 
                                   ring-slate-200 dark:ring-slate-800 bg-secondary dark:bg-primary'
          >
            <FaGraduationCap className='text-[1.2rem] text-surface dark:text-background' />
          </span>
          <h3 className=' flex items-center mb-1 text-xl sm:text-3xl font-medium text-slate-800 dark:text-gray-300'>
            M.S. Atmospheric Sciences
          </h3>
          <h3 className=' flex items-center mb-1 text-lg sm:text-xl font-medium text-secondary dark:text-primary'>
            National Taiwan University
          </h3>
          <time className='flex items-center mb-2 text-lg font-normal text-gray-400 dark:text-gray-500'>
            Sep. 2018 - Jul. 2020
          </time>
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <li className='ml-4 mb-2'>GPA : 4.13 / 4.3 ( 5 / 14 )</li>
            <li className='ml-4 mb-2'>Researched in the new particle formation from monoterpene ozonolysis.</li>
          </ul>
        </li>
        <li className='mb-10 ml-6 sm:ml-10 '>
          <span
            className='absolute w-8 h-8 flex items-center justify-center rounded-full -left-4 ring-8 
                                   ring-slate-200 dark:ring-slate-800 bg-secondary dark:bg-primary    '
          >
            <FaGraduationCap className='text-[1.2rem] text-surface dark:text-background' />
          </span>
          <h3 className=' flex items-center mb-1 text-xl sm:text-3xl font-medium text-slate-800 dark:text-gray-300'>
            B.S. Chemistry
          </h3>
          <h3 className=' flex items-center mb-1 text-lg sm:text-xl font-medium text-secondary dark:text-primary'>
            National Taiwan University
          </h3>
          <time className='flex items-center mb-2 text-lg font-normal text-gray-400 dark:text-gray-500'>
            Sep. 2015 - Jun. 2018
          </time>
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <li className='ml-4 mb-2'>GPA : 3.58 / 4.3 ( 28 / 67 )</li>
            <li className='ml-4 mb-2'>
              Transferred from Department of Chemistry, National Tsing Hua University (Sep. 2013 - Jun. 2015).
            </li>
          </ul>
        </li>
      </ul>
    </div>
  );
};

export default Profile;
