import Head from 'next/head';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import ScrollTrigger from 'react-scroll-trigger';
import { FaLinkedin, FaGithub, FaCopyright, FaBlackTie, FaGraduationCap } from 'react-icons/fa';
import {
  SiReact,
  SiTailwindcss,
  SiExpress,
  SiMongodb,
  SiFirebase,
  SiPython,
  SiJavascript,
  SiCplusplus,
  SiGnubash,
  SiLinux,
  SiRaspberrypi,
  SiDocker,
  SiBlender,
  SiAutodesk,
} from 'react-icons/si';
import ClipStudioPaint from '../public/assets/svg/clip-studio.svg';
import CircleProgress from '../components/CircleProgress';
import Expbar from '../components/Expbar';
import BackgroundImg from '../public/assets/png/street-rain.jpg';

const Profile = () => {
  const router = useRouter();

  useEffect(() => {
    console.log(router.asPath.replace('/', ''));
    if (router.asPath.replace('/', '')) {
      let elem = document.getElementById(router.asPath.replace('/', ''));
      if (elem) {
        elem.scrollIntoView({ behavior: 'smooth' });
      }
    } else {
      window.scrollTo({ top: 0, left: 0, behavior: 'smooth' });
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>AsGoshawk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full min-h-screen flex flex-col items-center justify-start pb-8'>
        <Banner />
        <About />
        <Skills />
        <Experience />
        <Education />
      </div>
    </>
  );
};

const Banner = () => {
  return (
    <div
      className='relative w-full h-screen pt-16 lg:pl-40 flex flex-col items-center justify-center bg-scroll bg-bottom bg-cover bg-no-repeat'
      style={{ backgroundImage: `url(${BackgroundImg.src})` }}
    >
      <div className='w-full md:w-5/6 lg:w-4/5 md:max-w-3xl h-60 relative py-2 mx-4 mt-32 md:mx-0 md:mt-0 bg-slate-700/40 rounded-none md:rounded-full flex flex-col md:items-end justify-evenly'>
        <div
          className='absolute rounded-full w-60 h-60 lg:w-80 lg:h-80 -top-56 inset-x-0 mx-auto  
                            md:left-0 md:top-auto md:mx-0 lg:-left-40 shadow-2xl overflow-hidden'
        >
          <img src='https://avatars.githubusercontent.com/u/42184309' alt='' />
        </div>
        <p className='text-xl lg:text-2xl text-gray-300 mx-auto md:ml-28 md:mr-28 lg:ml-48'>Hi there! I am</p>
        <h1 className='text-4xl lg:text-5xl font-bold text-primary mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          Ching-Wei Chu
        </h1>
        <p className='text-xl lg:text-2xl text-gray-300 mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          A Web developer from Taiwan.
        </p>
        <ul className='flex flex-wrap items-center text-sm text-gray-300 mx-auto md:ml-28 md:mr-28 lg:ml-48'>
          <li className='mr-4 md:mr-6 py-[auto]'>
            <a
              href='https://github.com/asgoshawk'
              className='block hover:text-primary transition-color ease-in-out duration-300'
              target='_blank'
              rel='noreferrer noopener'
            >
              <FaGithub className='text-2xl' />
            </a>
          </li>
          <li className='mr-4 md:mr-6 py-[auto]'>
            <a
              href='https://linkedin.com/in/asgoshawk'
              className='block hover:text-primary transition-color ease-in-out duration-300'
              target='_blank'
              rel='noreferrer noopener'
            >
              <FaLinkedin className='text-2xl' />
            </a>
          </li>
          <li className=''>
            <a
              href='https://cakeresume.com/me/asgoshawk'
              className='block hover:text-primary transition-color ease-in-out duration-300'
              target='_blank'
              rel='noreferrer noopener'
            >
              <FaCopyright className='text-2xl' />
            </a>
          </li>
        </ul>
      </div>
      <Link href='#about'>
        <a
          className='relative text-primary text-lg px-5 py-2 5 mt-16 rounded-lg border-primary border-2
                    hover:text-slate-900 hover:bg-primary/60 top-0 hover:top-0.5 transition-all ease-in-out duration-800'
        >
          About Me
        </a>
      </Link>
    </div>
  );
};

const About = () => {
  const [trigger1, setTrigger1] = useState(false);
  return (
    <div className='relative w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <div id='about' className='absolute -top-16 left-0'></div>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 py-4'>ABOUT</h1>

      <ScrollTrigger className='relative ' onEnter={() => setTrigger1(true)}>
        <div className='relative w-32 h-32'>
          <div
            className='absolute h-auto w-auto inset-0 m-2 rounded-full flex items-center justify-center
                                  bg-slate-200 dark:bg-slate-800 shadow-28 z-10'
          >
            <h1 className='text-slate-800 dark:text-gray-300'>123</h1>
          </div>
          <CircleProgress dashOffset={80} strokeColor={'stroke-secondary dark:stroke-primary'} trigger={trigger1} />
        </div>
      </ScrollTrigger>
    </div>
  );
};

const Skills = () => {
  const [trigger, setTrigger] = useState(false);
  return (
    <div className='relative w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <div className='absolute -top-16 left-0'></div>

      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 pb-2'>SKILLS</h1>
      <ScrollTrigger
        className='w-full my-2 lg:grid lg:grid-cols-2 lg:gap-2'
        onEnter={() => setTrigger(true)}
        // onExit={() => setTrigger(false)}
      >
        <div
          className='relative w-full px-4 py-4 rounded-2xl top-0 left-0
                     hover:shadow-lg hover:top-0.5 hover:left-0.5 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>Web Development</h1>
          <SkillItem text={'React'} percent={75} trigger={trigger} icon={<SiReact />} />
          <SkillItem text={'Tailwind CSS'} percent={70} trigger={trigger} icon={<SiTailwindcss />} />
          <SkillItem text={'Node.js / Express'} percent={65} trigger={trigger} icon={<SiExpress />} />
          {/* <SkillItem text={"InfluxDB"} percent={65} trigger={trigger} /> */}
          <SkillItem text={'MongoDB'} percent={60} trigger={trigger} icon={<SiMongodb />} />
          <SkillItem text={'Firebase'} percent={50} trigger={trigger} icon={<SiFirebase />} />
        </div>

        <div
          className='relative w-full px-4 py-4 rounded-2xl top-0 left-0
                                hover:shadow-lg hover:top-0.5 hover:left-0.5 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>Programing Language</h1>
          <SkillItem text={'Python'} percent={80} trigger={trigger} icon={<SiPython />} />
          <SkillItem text={'JavaScript'} percent={75} trigger={trigger} icon={<SiJavascript />} />
          <SkillItem text={'C / C++'} percent={50} trigger={trigger} icon={<SiCplusplus />} />
          <SkillItem text={'Bash Script'} percent={50} trigger={trigger} icon={<SiGnubash />} />
        </div>

        <div
          className='relative w-full px-4 py-4 rounded-2xl top-0 left-0
                                hover:shadow-lg hover:top-0.5 hover:left-0.5 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>System & Software</h1>
          <SkillItem text={'Linux'} percent={90} trigger={trigger} icon={<SiLinux />} />
          <SkillItem text={'Raspberry Pi'} percent={85} trigger={trigger} icon={<SiRaspberrypi />} />
          <SkillItem text={'Docker'} percent={50} trigger={trigger} icon={<SiDocker />} />
        </div>

        <div
          className='relative w-full px-4 py-4 rounded-2xl top-0 left-0
                                hover:shadow-lg hover:top-0.5 hover:left-0.5 transition-all ease-in-out duration-800'
        >
          <h1 className=' text-2xl font-medium text-slate-800 dark:text-gray-300 mb-2'>Other</h1>
          <SkillItem text={'Clip Studio Paint'} percent={65} trigger={trigger} icon={<ClipStudioPaint />} />
          <SkillItem text={'AutoCAD'} percent={65} trigger={trigger} icon={<SiAutodesk />} />
          <SkillItem text={'Blender'} percent={60} trigger={trigger} icon={<SiBlender />} />
          {/* <SkillItem text={"DaVinci Resolve"} percent={60} trigger={trigger} /> */}
        </div>
      </ScrollTrigger>
    </div>
  );
};

const SkillItem = ({ text, icon, percent, trigger }) => {
  return (
    <div className='mx-auto w-5/6 my-4 flex items-center wrap justify-center'>
      <div className='text-2xl text-slate-800 dark:text-gray-300 mr-8'>{icon}</div>
      <div className='w-5/6'>
        <p className='mb-1  text-md text-slate-800 dark:text-gray-300'> {text}</p>
        <Expbar width={percent} barColor={'bg-secondary dark:bg-primary'} isTrigger={trigger} />
      </div>
    </div>
  );
};

const Experience = () => {
  return (
    <div className='w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 py-4'>EXPERIENCE</h1>
      <ul className='relative ml-auto w-11/12 my-4 border-l-2 border-gray-400 dark:border-gray-500'>
        <li className='mb-10 ml-10 '>
          <span
            className='absolute w-8 h-8 flex items-center justify-center rounded-full -left-4 ring-8 
                                   ring-slate-200 dark:ring-slate-800 bg-secondary dark:bg-primary'
          >
            <FaBlackTie className='text-[1.2rem] text-surface dark:text-background' />
          </span>
          <h3 className=' flex items-center mb-1 text-3xl font-semibold text-slate-800 dark:text-gray-300'>
            Research Assistant (RDSS)
          </h3>
          <h3 className=' flex items-center mb-1 text-xl font-semibold text-secondary dark:text-primary'>
            National Taiwan University
          </h3>
          <time className='flex items-center mb-2 text-lg font-normal text-gray-400 dark:text-gray-500'>
            Sep. 2020 - May 2022
          </time>
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <p className='mb-1 font-semibold'>Instrument Development</p>
            <li className='ml-4 mb-2'>Build air sampling system and prepare control GUI using Tkinter.</li>
            <li className='ml-4 mb-2'>
              Build dashboard website for Air Quality Box (AQB) using common JavaScript/CSS/HTML.
            </li>
            <li className='ml-4 mb-2'>
              Handle AQB data restoration using Docker-based InfluxDB, and build API for dashboard with Node.js.
            </li>
            <li className='ml-4 mb-2'>
              Improve the housing of AQB with 3D-printed cover (Blender) and acryic mounting board (AutoCAD).
            </li>
            <li className='ml-4 mb-2'>Improve remote connection issue in field study with openVPN.</li>
          </ul>
          <br />
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <p className='mb-1 font-semibold'>Computing Machine Maintenance</p>
            <li className='ml-4 mb-2'>Hardware build and operating system (CentOS and Ubuntu) installation.</li>
            <li className='ml-4 mb-2'>Compile and test 16 softwares.</li>
          </ul>
          <br />
          <ul className='text-base font-normal text-gray-600 dark:text-gray-300 list-disc'>
            <p className='mb-1 font-semibold'>Others</p>
            <li className='ml-4 mb-2'>
              Air pollution hands-on course with Raspberry Pi (from serial communication protocols to webhook with Flask
              and Dialogflow).
            </li>
            <li className='ml-4 mb-2'>Scientific manuscript of model simulation.</li>
          </ul>
        </li>
      </ul>
    </div>
  );
};

const Education = () => {
  return (
    <div className='w-full my-8 px-4 md:px-0 md:w-5/6 lg:w-4/5 md:max-w-5xl'>
      <h1 className='text-4xl md:text-5xl font-thin text-slate-800 dark:text-gray-300 py-4'>EDUCATION</h1>
      <ul className='relative ml-auto w-11/12 my-4 border-l-2 border-gray-400 dark:border-gray-500'>
        <li className='mb-10 ml-10 '>
          <span
            className='absolute w-8 h-8 flex items-center justify-center rounded-full -left-4 ring-8 
                                   ring-slate-200 dark:ring-slate-800 bg-secondary dark:bg-primary'
          >
            <FaGraduationCap className='text-[1.2rem] text-surface dark:text-background' />
          </span>
          <h3 className=' flex items-center mb-1 text-3xl font-semibold text-slate-800 dark:text-gray-300'>
            M.S. Atmospheric Sciences
          </h3>
          <h3 className=' flex items-center mb-1 text-xl font-semibold text-secondary dark:text-primary'>
            National Taiwan University
          </h3>
          <time className='flex items-center mb-2 text-lg font-normal text-gray-400 dark:text-gray-500'>
            Sep. 2018 - Jul. 2020
          </time>

          <p className='text-base font-normal text-gray-600 dark:text-gray-300'>
            Researched in the new particle formation from monoterpene ozonolysis.
          </p>
        </li>
        <li className='mb-10 ml-10 '>
          <span
            className='absolute w-8 h-8 flex items-center justify-center rounded-full -left-4 ring-8 
                                   ring-slate-200 dark:ring-slate-800 bg-secondary dark:bg-primary    '
          >
            <FaGraduationCap className='text-[1.2rem] text-surface dark:text-background' />
          </span>
          <h3 className=' flex items-center mb-1 text-3xl font-semibold text-slate-800 dark:text-gray-300'>
            B.S. Chemistry
          </h3>
          <h3 className=' flex items-center mb-1 text-xl font-semibold text-secondary dark:text-primary'>
            National Taiwan University
          </h3>
          <time className='flex items-center mb-2 text-lg font-normal text-gray-400 dark:text-gray-500'>
            Sep. 2015 - Jun. 2018
          </time>
          <p className='text-base font-normal text-gray-600 dark:text-gray-300'>
            Transferred from Department of Chemistry, National Tsing Hua University (Sep. 2013 - Jun. 2015).
          </p>
        </li>
      </ul>
    </div>
  );
};

export default Profile;
